spring:
  rabbitmq:
    host: 49.234.211.99
    username: admin
    password: admin
    port: 5672
    publisher-returns: true  #回退消息给生产者
    publisher-confirm-type: correlated   #none 禁用发布确认模式，是默认值
                                         #correlated 发布消息成功到交换器后会触发回调方法
                                         #simple  单个确认
